name: CD
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    name: Deploy Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull nazmialtun/testokur-captcha:latest
            docker stop testokur-captcha && docker rm testokur-captcha --force
            docker run -d  \
            --name testokur-captcha \
            --restart=always  \
            --network=testokur \
            --env-file /home/env/captcha.env \
            --network-alias=testokur-captcha \
            nazmialtun/testokur-captcha:latest